### ISSUE TITLE
Is this going to support Django 2?

### ISSUE THREAD

**Issue by AdrianMuntean** [matthiask/django-admin-sso#3]

**Comment by matthiask** [comment]
I'd appreciate a pull request!

Otherwise I'll get to it when I get to it. I have mostly switched to django-authlib's authlib.admin_oauth module personally so it's not very high priority to me.

(Updating the library for Django 2.0 or even 2.2 and dropping support for older versions if it makes things easier would be absolutely fine.)

**Comment by AdrianMuntean** [comment]
I've looked at django-authlib and it seems to be the proper choice, thanks 👍
