### ISSUE TITLE
Provide error message to user on failed login

### ISSUE THREAD

**Issue by andymccurdy** [matthiask/django-admin-sso#5]
It would be nice to be able to display an error message to the user on the login form if their attempted SSO login failed for one reason or another. Currently on any failure the browser is redirected back to the admin index page.

I was initially going to try subclassing the included Auth backend and adding a message via the Django messages framework, but `authenticate()` doesn't receive a `request` which is required for messages to work.

I could implement my own `end` view and add error messages at the various failure points, but I'd prefer not to own that much of the OAuth logic in my app.

Perhaps making `end` a class-based view where users can subclass and provide error messages via the view's attributes would work. Or adding additional settings for error messages that the existing `end` view uses would also work. Though I'm not sure if you want this lib tied to Django's messaging framework or not.

Happy to put together a PR if you would like this functionality.

**Comment by matthiask** [comment]
Thanks for the report!

> I was initially going to try subclassing the included Auth backend and adding a message via the Django messages framework, but authenticate() doesn't receive a request which is required for messages to work.

I think that's an oversight.

```
docs/releases/1.11.txt:864:* :func:`~django.contrib.auth.authenticate` now passes a ``request`` argument
docs/releases/1.11.txt:865:  to the ``authenticate()`` method of authentication backends. Support for
docs/releases/1.11.txt-866-  methods that don't accept ``request`` as the first positional argument will
docs/releases/1.11.txt-867-  be removed in Django 2.1.
```

Our model backend respectively the way we're calling `authenticate()` should probably be updated to always pass a request.

Yes, please submit a PR. Such a feature doesn't even have to be configurable in my opinion. Showing an error would be the right thing to do and is an improvement which nobody (tm) should want to deactivate again.

(Btw, the reason why this didn't come up yet may be because we have mostly switched to django-authlib's admin support, see https://django-authlib.readthedocs.io/en/latest/#admin-oauth2 , but django-admin-sso is still maintained.)
